version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python -m notification_system.library_bot &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

  celery_worker:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: celery -A library_service.celery worker --loglevel=info --pool=solo
    restart: always
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

  celery_beat:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: celery -A library_service.celery beat --loglevel=info --schedule=/app/celerybeat-schedule
    restart: always
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6380:6379"